#!/usr/bin/env node

if (process.env.NODE_ENV !== 'production') {
  require('dotenv').config({ silent: true })
}

const db = require('../lib/db')
const User = require('../app/models/user')

const password = process.env.DEMO ? process.env.DEMOPASS : '*'

const createAdmin = () => User.create({
  username: 'admin',
  email: process.env.ADMIN_EMAIL,
  password,
  passwordConfirmation: password,
  admin: true,
  protected: true,
  activated: true,
  activatedAt: Date.now()
})

User.findOne({ username: 'admin' })
  .then(user => {
    if (user) return null
    return createAdmin()
  })
  .catch(err => {
    console.error(err.message)
  })
  .then(() => {
    db.connection.close()
  })
