#!/usr/bin/env node

if (process.env.NODE_ENV !== 'production') {
  require('dotenv').config({ silent: true })
}

const db = require('../lib/db')
const User = require('../app/models/user')

const createAdmin = () => User.create({
  username: 'admin',
  email: 'admin@example.com',
  password: 'qaz123',
  passwordConfirmation: 'qaz123',
  admin: true,
  activated: true,
  activatedAt: Date.now()
})

User.findOne({ username: 'admin' })
  .then(user => {
    if (user) return null
    return createAdmin()
  })
  .catch(err => {
    console.error(err.message)
  })
  .then(() => {
    db.connection.close()
  })
