#!/usr/bin/env node

if (process.env.NODE_ENV !== 'production') {
  require('dotenv').config({ silent: true })
}

const db = require('../lib/db')
const User = require('../app/models/user')

const createAdmin = () => User.create({
  username: 'admin',
  email: 'vigntom2708@gmail.com',
  password: '*',
  passwordConfirmation: '*',
  admin: true,
  protected: true,
  activated: true,
  activatedAt: Date.now()
})

const createNeitherUser = () => User.create({
  username: 'neither',
  email: 'vigntom2708@gmail.com',
  password: '*',
  passwordConfirmation: '*',
  protected: true,
  activated: true,
  activatedAt: Date.now()
})

User.findOne({ username: 'admin' })
  .then(user => {
    if (user) return null
    return createAdmin()
  })
  .then(() => User.findOne({ username: 'neither' }))
  .then(user => {
    if (user) return null
    return createNeitherUser()
  })
  .catch(err => {
    console.error(err.message)
  })
  .then(() => {
    db.connection.close()
  })
