#!/usr/bin/env node

if (process.env.NODE_ENV !== 'production') {
  require('dotenv').config({ silent: true })
}
const createDbConnection = require('../lib/db')

const db = createDbConnection()

db.connection
  .dropDatabase()
  .then((res) => {
    console.log(`Dropped database '${db.connection.db.databaseName}'`)
    db.connection.close()
  })
  .catch(err => console.error(err.message))
